### ISSUE TITLE
NoClassDefFoundError when upgrading to 16.0

### ISSUE THREAD

**Issue by phillip-kruger** [graphql-java/graphql-java#2107]
**Describe the bug**
When upgrading to 16.0, I get the following error on building my project:
```

java.lang.NoClassDefFoundError: com/google/common/math/IntMath
	at graphql.com.google.common.collect.ImmutableSet.maxRunBeforeFallback(ImmutableSet.java:741)
	at graphql.com.google.common.collect.ImmutableSet.access$000(ImmutableSet.java:53)
	at graphql.com.google.common.collect.ImmutableSet$RegularSetBuilderImpl.<init>(ImmutableSet.java:762)
	at graphql.com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:196)
	at graphql.com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:236)
	at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:116)
	at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:47)
	at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:640)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:622)
```

It's referring to the shaded guava classes, so I assume the issues is with https://github.com/graphql-java/graphql-java/pull/2086

**To Reproduce**
No sure how to reproduce it, as I am not sure what is the cause. It must be some combination of things I am using.

**Comment by dariuszkuc** [comment]
Hitting the same error. Based on the build file `com.google.common.math` is not shaded

https://github.com/graphql-java/graphql-java/blob/master/build.gradle#L96
```
// buiild.gradle 
    relocate('com.google.common', 'graphql.com.google.common') {
        include 'com.google.common.collect.*'
        include 'com.google.common.base.*'
    }
```

**Comment by phillip-kruger** [comment]
I am adding it and testing to see if that is all that is needed to fix this.

**Comment by bbakerman** [comment]
Thanks for reporting - we will fix this ASAP and get a 16.1 out

**Comment by bbakerman** [comment]
16.1 has been released

**Comment by phillip-kruger** [comment]
Thanks ! Working for me. Closing the issue.

**Comment by dariuszkuc** [comment]
Verified that `16.1` works for me as well. Thanks!
